[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Nikolaev <nikolaev.vitally@yandex.ru>"]
edition = "2018"

[dependencies]
sdl2 = "0.32"
gl = "0.6.0"
rand = "0.7"
num = "0.2.0"
tobj = "0.1.11"
num_cpus = "1.0"
